### ISSUE TITLE
Calling the `appcast` stanza is deprecated!

### ISSUE THREAD

**Issue by VincentSong915** [Bigwig-Club/homebrew-brew#30]
I use bigwig-club to install upic. Recently, when I'm trying to upgrade the upic or run the command `brew update`, a warning occurs, reading
```
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the bigwig-club/brew tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/bigwig-club/homebrew-brew/Casks/upic.rb:8
```
Is there anyway to fix it?

**Comment by uclort** [comment]
Fixed it, please run brew update and try again, the problem should be solved.

**Comment by VincentSong915** [comment]
Thanks! Appreciate your instant response and effort. The former warning did disappear. And there is another issue popped out. I'm trying to reinstall upic, running 'brew install bigwig-club/brew/upic --cask' after uninstalling it, The following message showed up
```
Warning: Cask 'upic' is unreadable: wrong number of arguments (given 1, expected 0)
==> Searching for similarly named casks...
Error: Cask 'upic' is unreadable: wrong number of arguments (given 1, expected 0)
```
Could you please have a look at it? Thanks again for your effort.

**Comment by uclort** [comment]
> Thanks! Appreciate your instant response and effort. The former warning did disappear. And there is another issue popped out. I'm trying to reinstall upic, running 'brew install bigwig-club/brew/upic --cask' after uninstalling it, The following message showed up
> 
> ```
> Warning: Cask 'upic' is unreadable: wrong number of arguments (given 1, expected 0)
> ==> Searching for similarly named casks...
> Error: Cask 'upic' is unreadable: wrong number of arguments (given 1, expected 0)
> ```
> 
> Could you please have a look at it? Thanks again for your effort.

The problem has been solved, but livecheck works a little differently, so please run brew update before proceeding.

**Comment by VincentSong915** [comment]
The problem is solved. Thanks!
